In [28]:
import numpy as np
import pandas as pd


data_new = np.arange(10, 25).reshape(5, 3)
df_new = pd.DataFrame(data_new, index=['grapefruit', 'lemon', 'lime', 'pear', 'peach'], columns=['shop_a', 'shop_b', 'shop_c'])

df_new['shop_d'] = np.nan
df_new.loc['apricot'] = np.arange(5, 9)
df_new.loc['plum'] = np.nan
df_new['shop_e'] = np.nan
df_new.loc['grapefruit', 'shop_d'] = 50

print("DataFrame with NaNs:")
display(df_new)

print("\nBoolean DataFrame for isnull():")
display(df_new.isnull())

print("\nBoolean DataFrame for notnull():")
display(df_new.notnull())

print("\n Sum of amount of NaN valuesper row:")
display(dfx.isnull().sum())

print("\n Total Number of NAaN values:")
display(dfx.isnull().sum().sum())

print("\n Number of reported values:")
display(dfx.count())

DataFrame with NaNs:

            shop_a  shop_b  shop_c  shop_d  shop_e
grapefruit    10.0    11.0    12.0    50.0     NaN
lemon         13.0    14.0    15.0     NaN     NaN
lime          16.0    17.0    18.0     NaN     NaN
pear          19.0    20.0    21.0     NaN     NaN
peach         22.0    23.0    24.0     NaN     NaN
apricot        5.0     6.0     7.0     8.0     NaN
plum           NaN     NaN     NaN     NaN     NaN

Boolean DataFrame for isnull():

            shop_a  shop_b  shop_c  shop_d  shop_e
grapefruit   False   False   False   False    True
lemon        False   False   False    True    True
lime         False   False   False    True    True
pear         False   False   False    True    True
peach        False   False   False    True    True
apricot      False   False   False   False    True
plum          True    True    True    True    True

Boolean DataFrame for notnull():

            shop_a  shop_b  shop_c  shop_d  shop_e
grapefruit    True    True    True    True   False
lemon         True    True    True   False   False
lime          True    True    True   False   False
pear          True    True    True   False   False
peach         True    True    True   False   False
apricot       True    True    True    True   False
plum         False   False   False   False   False

 Sum of amount of NaN valuesper row:

store1    1
store2    1
store3    1
store4    5
store5    7
dtype: int64

 Total Number of NAaN values:

np.int64(15)

 Number of reported values:

store1    6
store2    6
store3    6
store4    2
store5    0
dtype: int64

In [34]:
print("Non-null values from dfx.store4:")
display(dfx.store4[dfx.store4.notnull()])

print("\ndfx.store4 after dropna():")
display(dfx.store4.dropna())

print("\ndfx after dropping rows where all values are NaN:")
display(dfx.dropna(how='all'))

print("\ndfx after dropping columns where all values are NaN:")
display(dfx.dropna(how='all', axis=1))

print("\ndfx after dropping columns with fewer than 5 non-NaN values:")
display(dfx.dropna(thresh=5, axis=1))

ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)

print(f"\nMean of NumPy array (ar1): {ar1.mean()}")
print(f"\nMean of Pandas Series (ser1): {ser1.mean()}")

Non-null values from dfx.store4:

apple         20.0
watermelon    18.0
Name: store4, dtype: float64

dfx.store4 after dropna():

apple         20.0
watermelon    18.0
Name: store4, dtype: float64

dfx after dropping rows where all values are NaN:

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN

dfx after dropping columns where all values are NaN:

            store1  store2  store3  store4
apple         15.0    16.0    17.0    20.0
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
watermelon    15.0    16.0    17.0    18.0
oranges        NaN     NaN     NaN     NaN

dfx after dropping columns with fewer than 5 non-NaN values:

            store1  store2  store3
apple         15.0    16.0    17.0
banana        18.0    19.0    20.0
kiwi          21.0    22.0    23.0
grapes        24.0    25.0    26.0
mango         27.0    28.0    29.0
watermelon    15.0    16.0    17.0
oranges        NaN     NaN     NaN

Mean of NumPy array (ar1): nan

Mean of Pandas Series (ser1): 200.0

In [35]:
ser2 = dfx.store4

print("Original ser2:")
display(ser2)

print("\nSum of ser2:")
display(ser2.sum())

print("\nMean of ser2:")
display(ser2.mean())

print("\nCumulative sum of ser2:")
display(ser2.cumsum())

filledDf = dfx.fillna(0)
print("\ndfx after filling NaN values with 0:")
display(filledDf)

print("\nOriginal dfx (unchanged by fillna):")
display(dfx)

print("\nMean of original dfx (NaNs ignored):")
display(dfx.mean())

print("\nMean of filledDf (NaNs replaced by 0s):")
display(filledDf.mean())

print("\ndfx.store4 after forward fill:")
display(dfx.store4.fillna(method='ffill'))

print("\ndfx.store4 after backward fill:")
display(dfx.store4.fillna(method='bfill'))

Original ser2:

apple         20.0
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
watermelon    18.0
oranges        NaN
Name: store4, dtype: float64

Sum of ser2:

np.float64(38.0)

Mean of ser2:

np.float64(19.0)

Cumulative sum of ser2:

apple         20.0
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
watermelon    38.0
oranges        NaN
Name: store4, dtype: float64

dfx after filling NaN values with 0:

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     0.0
banana        18.0    19.0    20.0     0.0     0.0
kiwi          21.0    22.0    23.0     0.0     0.0
grapes        24.0    25.0    26.0     0.0     0.0
mango         27.0    28.0    29.0     0.0     0.0
watermelon    15.0    16.0    17.0    18.0     0.0
oranges        0.0     0.0     0.0     0.0     0.0

Original dfx (unchanged by fillna):

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

Mean of original dfx (NaNs ignored):

store1    20.0
store2    21.0
store3    22.0
store4    19.0
store5     NaN
dtype: float64

Mean of filledDf (NaNs replaced by 0s):

store1    17.142857
store2    18.000000
store3    18.857143
store4     5.428571
store5     0.000000
dtype: float64

dfx.store4 after forward fill:

/tmp/ipykernel_1501/442385042.py:29: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(dfx.store4.fillna(method='ffill'))

apple         20.0
banana        20.0
kiwi          20.0
grapes        20.0
mango         20.0
watermelon    18.0
oranges       18.0
Name: store4, dtype: float64

dfx.store4 after backward fill:

/tmp/ipykernel_1501/442385042.py:32: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(dfx.store4.fillna(method='bfill'))

apple         20.0
banana        18.0
kiwi          18.0
grapes        18.0
mango         18.0
watermelon    18.0
oranges        NaN
Name: store4, dtype: float64

In [36]:
ser_new = df_new['shop_d']

print("Original ser_new (df_new['shop_d']):")
display(ser_new)

print("\nSum of ser_new:")
display(ser_new.sum())

print("\nMean of ser_new:")
display(ser_new.mean())

print("\nCumulative sum of ser_new:")
display(ser_new.cumsum())

filledDf_new = df_new.fillna(0)
print("\ndf_new after filling NaN values with 0:")
display(filledDf_new)

print("\nOriginal df_new (unchanged by fillna):")
display(df_new)

print("\nMean of original df_new (NaNs ignored):")
display(df_new.mean())

print("\nMean of filledDf_new (NaNs replaced by 0s):")
display(filledDf_new.mean())

print("\ndf_new['shop_d'] after forward fill:")
display(df_new['shop_d'].fillna(method='ffill'))

print("\ndf_new['shop_d'] after backward fill:")
display(df_new['shop_d'].fillna(method='bfill'))

Original ser_new (df_new['shop_d']):

grapefruit    50.0
lemon          NaN
lime           NaN
pear           NaN
peach          NaN
apricot        8.0
plum           NaN
Name: shop_d, dtype: float64

Sum of ser_new:

np.float64(58.0)

Mean of ser_new:

np.float64(29.0)

Cumulative sum of ser_new:

grapefruit    50.0
lemon          NaN
lime           NaN
pear           NaN
peach          NaN
apricot       58.0
plum           NaN
Name: shop_d, dtype: float64

df_new after filling NaN values with 0:

            shop_a  shop_b  shop_c  shop_d  shop_e
grapefruit    10.0    11.0    12.0    50.0     0.0
lemon         13.0    14.0    15.0     0.0     0.0
lime          16.0    17.0    18.0     0.0     0.0
pear          19.0    20.0    21.0     0.0     0.0
peach         22.0    23.0    24.0     0.0     0.0
apricot        5.0     6.0     7.0     8.0     0.0
plum           0.0     0.0     0.0     0.0     0.0

Original df_new (unchanged by fillna):

            shop_a  shop_b  shop_c  shop_d  shop_e
grapefruit    10.0    11.0    12.0    50.0     NaN
lemon         13.0    14.0    15.0     NaN     NaN
lime          16.0    17.0    18.0     NaN     NaN
pear          19.0    20.0    21.0     NaN     NaN
peach         22.0    23.0    24.0     NaN     NaN
apricot        5.0     6.0     7.0     8.0     NaN
plum           NaN     NaN     NaN     NaN     NaN

Mean of original df_new (NaNs ignored):

shop_a    14.166667
shop_b    15.166667
shop_c    16.166667
shop_d    29.000000
shop_e          NaN
dtype: float64

Mean of filledDf_new (NaNs replaced by 0s):

shop_a    12.142857
shop_b    13.000000
shop_c    13.857143
shop_d     8.285714
shop_e     0.000000
dtype: float64

df_new['shop_d'] after forward fill:

/tmp/ipykernel_1501/3942185219.py:29: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(df_new['shop_d'].fillna(method='ffill'))

grapefruit    50.0
lemon         50.0
lime          50.0
pear          50.0
peach         50.0
apricot        8.0
plum           8.0
Name: shop_d, dtype: float64

df_new['shop_d'] after backward fill:

/tmp/ipykernel_1501/3942185219.py:32: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(df_new['shop_d'].fillna(method='bfill'))

grapefruit    50.0
lemon          8.0
lime           8.0
pear           8.0
peach          8.0
apricot        8.0
plum           NaN
Name: shop_d, dtype: float64